/** スキル / クラスエディタの createFieldRow 表示ラベル（JSON フィールド key → 日本語） */
export const EDITOR_FIELD_LABELS = {
  classId: "クラス ID",
  enemyId: "敵 ID",
  iconKey: "アイコンキー",
  exp: "経験値",
  chance: "発動確率 (0–1)",
  ratio: "倍率",
  jobTier: "ジョブ Tier",
  maxHp: "最大 HP",
  atk: "攻撃力",
  def: "防御力",
  res: "魔法耐性",
  "primary damageType": "primary ダメージ種",
  "primary atkScale": "primary ATK倍率",
  "primary hitCount": "primary 攻撃回数",
  "primary hitDurationSec": "primary 多段秒数",
  "primary targetShape": "primary ターゲット形状",
  "primary aoe 半径 px": "primary AoE 半径（px）",
  "maxCharges 加算": "最大チャージ加算",
  ignoredDefBonusScale: "DEF無視ボーナス倍率",
  "bonusBasicAttackHpRatio（省略可）": "通常攻撃 HP割合（省略可）",
  frontBlockAuraMagicBlock: "前列魔法 block 率",
  lastStandRecoveryHpRatio: "復活 HP 割合",
  lastStandRecoverySelfDamageTakenMultiplier: "自己被ダメ倍率",
  lastStandRecoveryFrontAllyDamageTakenMultiplier: "前列味方被ダメ倍率",
  lastStandRecoveryDurationSec: "効果時間（秒）",
  prideHpRatioMin: "HP割合下限",
  prideHealMultiplier: "回復倍率",
  coverHpRatioThreshold: "カバー HP割合しきい値",
  coverWaveLimit: "Wave 上限",
  lastStandGutsDurationSec: "効果時間（秒）",
  lastStandGutsEndStunSec: "終了時スタン（秒）",
  lastStandGutsEndKnockbackPx: "終了時ノックバック（px）",
  bloodlustBlockChance: "block 確率",
  bloodlustAtkBuffCurveExponent: "ATKバフ曲線指数",
  dotCompressRatio: "DoT圧縮率",
  debuffDotDurationSec: "DoT秒数",
  debuffDotDamageType: "DoTダメージ種",
  debuffDotFlavor: "DoTフレーバー",
  dotDurationMultiplierOnApply: "付与時 DoT 秒数倍率",
  dottedEnemyHealReceivedMultiplier: "DoT敵 被回復倍率",
  enemyDamageTakenMultiplier: "敵被ダメ倍率",
  barrierScale: "バリア倍率",
  redirectScale: "被ダメ redirect 倍率",
  perExtraTargetScale: "追加ターゲットあたり倍率",
  maxExtraTargets: "追加ターゲット上限",
  nextOutgoingDamageMultiplier: "次 outgoing ダメ倍率",
  fieldRadiusPx: "フィールド半径（px）",
  fieldDurationSec: "フィールド持続（秒）",
  stayTickIntervalSec: "stay tick 間隔（秒）",
  stayCompressRatioBonusPerTick: "stay 圧縮率加算（/tick）",
  compressRatio: "圧縮率",
  extendRatio: "延長倍率",
  harvestRatio: "収穫率",
  spreadRadiusPx: "spread 半径（px）",
  spreadDurationRatio: "spread 持続倍率",
  dotFlavor: "DoTフレーバー",
  herbalPotencyMaxStacks: "薬効 stack 上限",
  herbalPotencyHotPerStackPercent: "stack あたり HoT maxHp 加算",
  herbalPotencyHotTickSec: "aura HoT tick 間隔（秒）",
  herbalPotencyAccumulateSec: "薬効蓄積間隔（秒）",
  "herbalPotencyConstitutionThresholds（カンマ区切り）":
    "頑健 閾値（カンマ区切り）",
  "herbalPotencyConstitutionHpMultipliers（カンマ区切り）":
    "頑健 HP倍率（カンマ区切り）",
  herbalPotencyConstitutionDisplayName: "頑健 表示名",
  emberIgnitionThreshold: "種火 発火閾値",
  emberIgnitionAtkScale: "発火 ATK倍率",
} as const satisfies Record<string, string>;

export type EditorFieldLabelKey = keyof typeof EDITOR_FIELD_LABELS;

export function editorFieldLabel(key: EditorFieldLabelKey): string {
  return EDITOR_FIELD_LABELS[key];
}
