/** Victory / Wave 告知オーバーレイ共通タイミング（ms） */
export const ANNOUNCEMENT_FADE_IN_MS = 600;
export const ANNOUNCEMENT_HOLD_MS = 2500;
export const ANNOUNCEMENT_FADE_OUT_MS = 500;
export const ANNOUNCEMENT_FADE_OUT_START_MS =
  ANNOUNCEMENT_FADE_IN_MS + ANNOUNCEMENT_HOLD_MS;
export const ANNOUNCEMENT_TOTAL_MS =
  ANNOUNCEMENT_FADE_IN_MS + ANNOUNCEMENT_HOLD_MS + ANNOUNCEMENT_FADE_OUT_MS;

/** fade-out 開始から接敵までの待機（秒） */
export const POST_ANNOUNCEMENT_ENGAGE_DELAY_SEC = 0.25;
export const POST_ANNOUNCEMENT_ENGAGE_START_MS =
  ANNOUNCEMENT_FADE_OUT_START_MS + POST_ANNOUNCEMENT_ENGAGE_DELAY_SEC * 1000;

/** PartyDeploy 到達後、接敵開始までの待機（秒） */
export const POST_DEPLOY_SETTLE_DELAY_SEC = 1;
